aa: rand-m9-mstd0.5
amp: false
amp_dtype: float16
amp_impl: native
aot_autograd: false
aug_repeats: 0
aug_splits: 0
batch_size: 256
bce_loss: false
bce_target_thresh: null
bn_eps: null
bn_momentum: null
cats_path: dataset/optimize_labeled/2353_cats.txt
channels_last: false
checkpoint_hist: 10
class_map: ''
clip_grad: null
clip_mode: norm
color_jitter: 0.4
compute_by_cat: true
cooldown_epochs: 0
crop_pct: null
custom_aa: false
cutmix: 0.0
cutmix_minmax: null
data: null
data_classes: null
data_dir: dataset/optimize_labeled
dataset: txt_data
dataset_download: false
decay_epochs: 90
decay_milestones:
- 90
- 180
- 270
decay_rate: 0.973
device: cuda
dist_bn: reduce
drop: 0.0
drop_block: null
drop_connect: null
drop_path: null
epoch_repeats: 0.0
epochs: 30
eval_metric: top1
experiment: ''
fast_norm: false
feat_extract_dim: 128
finetune: false
fuser: ''
gp: null
grad_accum_steps: 1
grad_checkpointing: false
head_init_bias: null
head_init_scale: null
hflip: 0.3
img_size: 224
in_chans: null
infer_mode: val
initial_checkpoint: ''
input_size: null
interpolation: ''
jsd_loss: false
label_file: dataset/zero_dataset/label_names.csv
layer_decay: null
local_rank: 0
log_freq: 10
log_interval: 50
log_wandb: true
lr: null
lr_base: 0.00375
lr_base_scale: ''
lr_base_size: 1024
lr_cycle_decay: 0.5
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_k_decay: 1.0
lr_noise:
- 0.07
- 0.15
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean: null
min_lr: 0
mixup: 0.0
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: mobilenetv4_hybrid_medium.e200_r256_in12k_ft_in1k
model_classes: 2353
model_ema: true
model_ema_decay: 0.9999
model_ema_force_cpu: false
model_kwargs: {}
momentum: 0.9
multilabel: null
no_aug: false
no_ddp_bb: false
no_prefetcher: false
no_resume_opt: false
num_choose: null
num_classes: 2351
num_gpu: 8
opt: rmsproptf
opt_betas: null
opt_eps: 0.001
opt_kwargs: {}
options: null
output: output/ckpts
pass_path: ''
patience_epochs: 10
pin_mem: false
pretrained: true
ratio:
- 0.75
- 1.3333333333333333
real_labels: ''
recount: 1
recovery_interval: 0
remode: pixel
reparam: false
reprob: 0.2
resplit: false
results_file: ''
results_format: csv
resume: ''
retry: true
save_images: false
scale:
- 0.4
- 1.0
sched: cosine
sched_on_updates: false
seed: 42
smoothing: 0.1
split: validation
split_bn: false
start_epoch: null
std: null
sync_bn: false
synchronize_step: false
tensorboard: ''
test_pool: false
tf_preprocessing: false
torchcompile: null
torchscript: false
tqdm_disabled: false
train_interpolation: random
train_split: train
tta: 0
use_ema: true
use_multi_epochs_loader: false
use_train_size: false
val_split: validation
valid_labels: ''
validation_batch_size: null
vflip: 0.3
warmup_epochs: 0
warmup_lr: 1.0e-05
warmup_prefix: false
weight_decay: 1.0e-05
worker_seeding: all
workers: 4
model_ema_warmup: false
pretrained_path: null
tqdm_disabled: false
weights_only: null
